import type { Metadata } from "next";
import "./globals.css";

import { Nunito_Sans } from "next/font/google";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const nunitoSans = Nunito_Sans({
  subsets: ["latin"], // Specify the character subset
  weight: ["200", "300", "400", "700", "1000"], // Specify the desired weights
  style: ["normal", "italic"], // Include both normal and italic styles
  display: "swap", // Ensures text remains visible during font loading [[10]]
  variable: "--font-nunito-sans", // Optional: Define a CSS variable
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunitoSans.variable} font-sans bg-background theme-custom`}
      >
        <div className="fixed inset-0 bg-dots pointer-events-none z-0" />
        <div className="relative z-10">{children}</div>
      </body>
    </html>
  );
}
